FROM demoregistry.dataman-inc.com/library/centos7-base:20160602202509
MAINTAINER yqguo yqguo@dataman-inc.com

WORKDIR /

COPY omega-billing/omega-billing /
COPY omega-billing/sql /sql
ENTRYPOINT ["./omega-billing"]

#demoregistry.dataman-inc.com/shurenyun/centos7-omega-billing:tag
